version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-use
    versions:
    - 15.3.8
    - 17.1.1
    - 17.2.3
  - dependency-name: apollo-server-core
    versions:
    - 2.16.1
    - 2.21.2
    - 2.22.2
  - dependency-name: react-native-webview
    versions:
    - 11.2.0
    - 11.2.1
    - 11.2.3
    - 11.3.1
  - dependency-name: react-native-web
    versions:
    - 0.14.10
    - 0.14.13
    - 0.15.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
  - dependency-name: react-native-screens
    versions:
    - 2.16.1
    - 2.17.1
  - dependency-name: class-transformer
    versions:
    - 0.3.2
  - dependency-name: react-native
    versions:
    - 0.63.4
  - dependency-name: react-native-safe-area-context
    versions:
    - 3.1.9
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
