version: "3.3"
services:
  db:
    image: postgres
    env_file:
      - ./server/.env
    ports:
      - 5432:5432

  prime-server:
    image: gyash24x7/shaastra-prime
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: production
